@host = http://localhost
@port = 3000
@endpoint= {{host}}:{{port}}

### register employee
POST {{endpoint}}/api/employee/register
Content-Type: application/json

{
    "name": "aliif arief",
    "email": "me@aliifam.com",
    "password": "Al1ifam"
}

### login employee
POST {{endpoint}}/api/employee/login
Content-Type: application/json

{
    "email": "me@aliifam.com",
    "password": "Al1ifam"
}

### get current employee profile
GET {{endpoint}}/api/employee/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsdXBuNm4ycDAwMDBzZWM0Y2U2NG9kMDciLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3MTI1MDE2NDAsImV4cCI6MTcxMjUwNTI0MH0.yBvNzbvOVKfiQJbj-sTIrV_fLwodQ1ZcVssdPYVrM6M

### create new company
POST {{endpoint}}/api/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsdXBuNm4ycDAwMDBzZWM0Y2U2NG9kMDciLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3MTI1MDE2NDAsImV4cCI6MTcxMjUwNTI0MH0.yBvNzbvOVKfiQJbj-sTIrV_fLwodQ1ZcVssdPYVrM6M

{
    "name": "PT. Aliifam",
    "address": "Jl. Aliifam No. 1"
}
